logging:
  level:
    root: ERROR
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
security:
  basic:
    enabled: false
